# Generated by Django 4.1.5 on 2023-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=119),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=119),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=119),
        ),
    ]
